name = "compression"
description = "Algorithms for data compression"
version = "0.1.0-dev"

authors = ["Miko Elbrecht"]
maintainers = ["Miko Elbrecht <pmt.mailservice@gmail.com>"]
maintainers-logins = ["meownium"]
licenses = "GPL-3.0-or-later"
website = "https://javart.zip"
tags = ["jpeg", "zlib", "deflate", "inflate", "flate", "compression"]

[[depends-on]]
checksum = "~0.1.0-dev"

[[pins]]
checksum = { path='../checksum' }
